routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if(!defined('STATIC_DIR')) define('STATIC_DIR','public/');
Route::get('/','HomeController@index');

Auth::routes();

//example of front end user login
//Route::get('/frontend/login','Auth\LoginController@showUserLogin')->name('user.login');

Route::group(['prefix' => 'admin' , 'middleware' => 'auth' , 'as' => 'admin.' ],function(){

    Route::get('/dashboard','HomeController@showDashboard')->name('dashboard')->middleware('auth');
    Route::get('/dashboard','HomeController@showDashboard')->name('dashboard');



//user crud operation routes
    //user routes
    Route::group(['prefix' => 'user','as' => 'user.'],function(){
        Route::get('/', ['uses' => 'UserController@list' , 'as' => 'list']);
//        Route::get('/user/list','UserController@list')->name('user.list');
        Route::get('/update/{id}','UserController@edit')->name('edit');
        Route::post('/update','UserController@updateUser')->name('update');
        Route::post('/delete','UserController@deleteUser')->name('delete');

        Route::post('/user/register','UserController@registerUser')->name('register');
    });
//end user routes

    //banner routes
    Route::group(['prefix' => 'banner','as' => 'banner.'],function(){
        Route::get('/list', ['uses' => 'BannerController@list' , 'as' => 'list']);
        Route::get('/', ['uses' => 'BannerController@addBanner' , 'as' => 'add-banner']);
        Route::post('/add', ['uses' => 'BannerController@postAddBanner' , 'as' => 'insert-banner']);
    });
    //end banner routes

    //category  routes
    Route::group(['prefix' => 'category','as' => 'category.'],function(){
        Route::get('/list', ['uses' => 'CategoryController@list' , 'as' => 'list']);
        Route::get('/add', ['uses' => 'CategoryController@showCategoryForm' , 'as' => 'show-category-form']);
        Route::post('/add', ['uses' => 'CategoryController@postAddCategory' , 'as' => 'add-category']);
        Route::get('/edit/{id}', ['uses' => 'CategoryController@getEditCategory' , 'as' => 'edit-category']);
        Route::post('/edit', ['uses' => 'CategoryController@postEditCategory' , 'as' => 'store-category']);

        //ajax routes
        Route::post('/category/id', ['uses' => 'CategoryController@getCategoryById' , 'as' => 'get-sub-category-by-id']);



        Route::post('/delete', ['uses' => 'CategoryController@deleteCategory' , 'as' => 'delete-category']);
    });
//    end category routes

    //product  routes
    Route::group(['prefix' => 'product','as' => 'product.'],function(){
        Route::get('/list', ['uses' => 'ProductController@list' , 'as' => 'list']);
        Route::get('/add', ['uses' => 'ProductController@showProductForm' , 'as' => 'show-product-form'])->middleware('can:banner');
       Route::post('/add', ['uses' => 'ProductController@postAddCategory' , 'as' => 'add-product']);
//        Route::get('/edit/{id}', ['uses' => 'CategoryController@getEditCategory' , 'as' => 'edit-category']);
//        Route::post('/edit', ['uses' => 'CategoryController@postEditCategory' , 'as' => 'store-category']);


        Route::post('/delete', ['uses' => 'CategoryController@deleteCategory' , 'as' => 'delete-category']);
    });
//    end product routes


});

Route::get('/home', 'HomeController@index')->name('home');


//end user crud operation routes
//Route::group(['prefix' => 'user'], function({
//    Route::get('/list','UserController@list')->name('user.list');
//    Route::get('/edit','UserController@edit')->name('user.edit');
//
//});
//Route::get('/user/edit','UserController@edit')->name('user.edit');
//Route::get('/user/delete','UserController@delete')->name('user.delete');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

//    public function category()
//    {
//        return $this->hasOne('App\Category','id','added_by');
//    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;


use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{

    public function list(){

        $data['user'] = User::all();
//        dd($user);
        return view("user.list",$data);
//        $user = User::all();
//        return view("user.list")->with('user',$user);
    }

    public function edit($id){
        $data['user'] = User::find($id);
//        dd($user);

//        $user = User::where('id',$id)->all();
        return view('user.edit',$data);
    }

    public function updateUser(Request $request){
//        dd($request->all());

        $request->validate([
            'user_id' => 'required',
            'name' => 'required|max:25',
            'password' => 'required|confirmed',
            'contact' => 'required|min:5|max:12'
        ]);


        $user = User::find($request->user_id);
        $user->name = $request->name;
        $user->password = Hash::make($request->password);
        $user->contact_number = $request->contact;

        if(($request->user_avatar != null)){
            //delete previous user profile
            Storage::delete('public/'.$user->user_avatar);
            $user->user_avatar = $request->file('user_avatar')->store('users','public');
        }
        $user->save();

        return redirect()->route('admin.user.list');
    }

    public function deleteUser(Request $request){
//        dd($request->all());
        $user_info = User::find($request->user_id);
        Storage::delete('public/'.$user_info->user_avatar);
        $user_info->delete();

       return redirect()->route('admin.user.list');
    }

    public function registerUser(Request $request){
//        dd($request->all());

        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'contact' => ['required','string'],
//            'user_avatar' => 'required|mimes:jpeg,png,gif,jpg'
        ]);

        if(isset($request->user_avatar)){
            $request->validate([
                'user_avatar' => 'required|mimes:jpeg,png,gif,jpg'
            ]);
        }

//        dd('validated');
        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;

        $user->contact_number = $request->contact;
        $user->password = Hash::make($request->password);

        if(($request->user_avatar != null)){
            $user->user_avatar = $request->file('user_avatar')->store('users','public');
//            $request->file('image')->store('offers', 'public');
//            $user->user_avatar = $path;
        }

//        $user->user_avatar = $request->name;
        $user->save();

        return redirect()->route('admin.user.list');


    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('page_title')
    User Edit
@endsection

@section('page_heading')
    User Edit
@endsection

@section('content')
    <div class="white-box">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">

                        <div class="card-header">
                            <a href="{{ route('admin.user.list') }}" class="btn btn-info"><i class="fa fa-arrow-circle-left"></i> Back</a>
                            <br>
                            <br>
                        </div>

                        <div class="card-body">
                            <form method="POST" action="{{ route('admin.user.update') }}" enctype="multipart/form-data">
                                @csrf

                                <input type="hidden" value="{{$user->id}}" name="user_id">

                                <div class="form-group row" >
                                    <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                                    <div class="col-md-6">
                                        <input  type="text" class="form-control " name="name" value="{{ $user->name }}" >

                                        @if($errors->has('name'))
                                            <span class="invalid-feedback" role="alert" style="color:red;">
                                                <b> * {{ $errors->first('name') }}</b>
                                            </span>
                                        @endif

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                    <div class="col-md-6">
                                        <input  type="email" readonly class="form-control " name="email" value="{{ $user->email }}" required >

                                        @if($errors->has('email'))
                                            <span class="invalid-feedback" role="alert" style="color:red;">
                                                <b> * {{ $errors->first('email') }}</b>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="" class="col-md-4 col-form-label text-md-right">Contact Number</label>

                                    <div class="col-md-6">
                                        <input  type="number" class="form-control  is-invalid " name="contact" value="{{ $user->contact_number }}"  placeholder="Enter Phone Number">

                                        @if($errors->has('contact'))
                                            <span class="invalid-feedback" role="alert" style="color:red;">
                                                <b> * {{ $errors->first('contact') }}</b>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="password" class="col-md-4 col-form-label text-md-right"> New Password</label>

                                    <div class="col-md-6">
                                        <input type="password" class="form-control" name="password" >

                                        @if($errors->has('password'))
                                            <span class="invalid-feedback" role="alert" style="color:red;">
                                                 *<b> {{ $errors->first('password') }} </b>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                    <div class="col-md-6">
                                        <input  type="password" class="form-control" name="password_confirmation" >
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="" class="col-md-4 col-form-label text-md-right">{{ __('Image Upload') }}</label>

                                    <div class="col-md-6">
                                        <input type="file" name="user_avatar">
                                    </div>
                                </div>

                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-success">
                                            Update
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')

@endsection

resources/views/user/list.blade.php
@extends('layouts.app')

@section('css')
    <link href="{{ asset(STATIC_DIR."assets/plugins/bower_components/datatables/jquery.dataTables.min.css") }}" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css" rel="stylesheet" type="text/css" />
@endsection

@section('page_title')
    User List
@endsection

@section('page_heading')
    User List
@endsection

@section('content')
    <div class="row helo">
        <div class="white-box">
            <table class="table table-bordered  " id="user-datatable">
                <thead>
                    {{--<tr>--}}
                        <th>S.N.</th>
                        <th>Profile Image</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Created At</th>
                        <th>Action</th>
                    {{--</tr>--}}
                </thead>

                <tbody>

                @foreach($user as $value)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>
                            @if($value->user_avatar == null)
                                <img src="{{asset(STATIC_DIR.'/image_upload/default_user.png')}}" alt="" style="max-width: 100px;" class="img img-responsive">
                            @else
                                <img src="{{asset(STATIC_DIR.'/storage/'.$value->user_avatar)}}" alt="" style="max-width: 100px;" class="img img-responsive">
                            @endif
                        </td>
                        <td>{{$value->name}}</td>
                        <td>{{$value->email}}</td>
                        <td>{{$value->created_at}}</td>
                        <td><a href="{{route('admin.user.edit',$value->id)}}"> Edit</a>
                            ||
{{--                            <a href="{{route('user.delete',$value->id)}}">Delete</a></td>--}}
                            {{--<a href="#deleteUser">Delete</a></td>--}}
                        {{--<button type="button"  class="btn btn-primary" data-toggle="modal" data-target="#deleteUser" data-="@mdo">Delete</button>--}}
                            <a  href="#deleteUser"  class="" data-toggle="modal"  data-id="{{$value->id}}" data-name="{{$value->name}}">Delete</a>

                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>


    <div class="modal fade" id="deleteUser" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">User Delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('admin.user.delete') }}" method="POST">
                    @csrf
                    <div class="modal-body">
                        <input type="hidden" name="user_id" id="user_id">
                        <p>Are you sure to delete user <span class="user_name"></span>?</p>
                    </div>
                    <div class="modal-footer" style="text-align: left;">
                        <button type="submit" class="btn btn-danger"><i class="fa fa-check-circle"> Yes</i></button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-times-circle"> No</i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection


@section('scripts')
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/datatables/jquery.dataTables.min.js') }}"></script>


    <script>
        $(document).ready(function() {
            $('#user-datatable').DataTable();
        });



        $('#deleteUser').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var id = button.data('id');
            var name = button.data('name');
            // var recipient = button.data('whatever') // Extract info from data-* attributes
            // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
            // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
            var modal = $(this)
            modal.find('#user_id').val(id);
            modal.find('.user_name').text(name);
        })
    </script>
@endsection

resources/views/user/user-register.blade.php
@extends('layouts.app')

@section('page_title')
    User Register
@endsection

@section('css')

@endsection

@section('page_heading')
    Ecommerce || User Registration
@endsection


@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Register') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('admin.user.register') }}" enctype="multipart/form-data">
                            @csrf

                            <div class="form-group row" >
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="" class="col-md-4 col-form-label text-md-right">Contact Number</label>

                                <div class="col-md-6">
                                    <input  type="number" class="form-control @error('email') is-invalid @enderror" name="contact" value="{{ old('contact') }}" required autocomplete="email" placeholder="Enter Phone Number">

                                    {{--@error('email')--}}
                                    {{--<span class="invalid-feedback" role="alert">--}}
                                        {{--<strong>{{ $message }}</strong>--}}
                                    {{--</span>--}}
                                    {{--@enderror--}}
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>



                            <div class="form-group row">
                                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="" class="col-md-4 col-form-label text-md-right">{{ __('Image Upload') }}</label>

                                <div class="col-md-6">
                                    <input type="file" name="user_avatar">
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="javascript/css">

    </script>

    <script src="{{asset(STATIC_DIR.'assets/js/custom.min.js')}}"></script>