routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if(!defined('STATIC_DIR')) define('STATIC_DIR','public/');
Route::get('/','HomeController@index');

Auth::routes();

//example of front end user login
//Route::get('/frontend/login','Auth\LoginController@showUserLogin')->name('user.login');

Route::group(['prefix' => 'admin' , 'middleware' => 'auth' , 'as' => 'admin.' ],function(){

    Route::get('/dashboard','HomeController@showDashboard')->name('dashboard')->middleware('auth');
    Route::get('/dashboard','HomeController@showDashboard')->name('dashboard');



//user crud operation routes
    //user routes
    Route::group(['prefix' => 'user','as' => 'user.'],function(){
        Route::get('/', ['uses' => 'UserController@list' , 'as' => 'list']);
//        Route::get('/user/list','UserController@list')->name('user.list');
        Route::get('/update/{id}','UserController@edit')->name('edit');
        Route::post('/update','UserController@updateUser')->name('update');
        Route::post('/delete','UserController@deleteUser')->name('delete');

        Route::post('/user/register','UserController@registerUser')->name('register');
    });
//end user routes

    //banner routes
    Route::group(['prefix' => 'banner','as' => 'banner.'],function(){
        Route::get('/list', ['uses' => 'BannerController@list' , 'as' => 'list']);
        Route::get('/', ['uses' => 'BannerController@addBanner' , 'as' => 'add-banner']);
        Route::post('/add', ['uses' => 'BannerController@postAddBanner' , 'as' => 'insert-banner']);
    });
    //end banner routes

    //category  routes
    Route::group(['prefix' => 'category','as' => 'category.'],function(){
        Route::get('/list', ['uses' => 'CategoryController@list' , 'as' => 'list']);
        Route::get('/add', ['uses' => 'CategoryController@showCategoryForm' , 'as' => 'show-category-form']);
        Route::post('/add', ['uses' => 'CategoryController@postAddCategory' , 'as' => 'add-category']);
        Route::get('/edit/{id}', ['uses' => 'CategoryController@getEditCategory' , 'as' => 'edit-category']);
        Route::post('/edit', ['uses' => 'CategoryController@postEditCategory' , 'as' => 'store-category']);

        //ajax routes
        Route::post('/category/id', ['uses' => 'CategoryController@getCategoryById' , 'as' => 'get-sub-category-by-id']);



        Route::post('/delete', ['uses' => 'CategoryController@deleteCategory' , 'as' => 'delete-category']);
    });
//    end category routes

    //product  routes
    Route::group(['prefix' => 'product','as' => 'product.'],function(){
        Route::get('/list', ['uses' => 'ProductController@list' , 'as' => 'list']);
        Route::get('/add', ['uses' => 'ProductController@showProductForm' , 'as' => 'show-product-form'])->middleware('can:banner');
       Route::post('/add', ['uses' => 'ProductController@postAddCategory' , 'as' => 'add-product']);
//        Route::get('/edit/{id}', ['uses' => 'CategoryController@getEditCategory' , 'as' => 'edit-category']);
//        Route::post('/edit', ['uses' => 'CategoryController@postEditCategory' , 'as' => 'store-category']);


        Route::post('/delete', ['uses' => 'CategoryController@deleteCategory' , 'as' => 'delete-category']);
    });
//    end product routes


});

Route::get('/home', 'HomeController@index')->name('home');


//end user crud operation routes
//Route::group(['prefix' => 'user'], function({
//    Route::get('/list','UserController@list')->name('user.list');
//    Route::get('/edit','UserController@edit')->name('user.edit');
//
//});
//Route::get('/user/edit','UserController@edit')->name('user.edit');
//Route::get('/user/delete','UserController@delete')->name('user.delete');

resources/views/layouts/_partials/footer.blade.php
<footer class="footer text-center"> 2019 &copy; Ecommerce </footer>

resources/views/layouts/_partials/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" type="image/png" sizes="16x16" href="../plugins/images/favicon.png">
    <title>Ecommerce || @yield('page_title')</title>
    <!-- Bootstrap Core CSS -->
    <link href="{{asset(STATIC_DIR.'assets/bootstrap/dist/css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="{{asset(STATIC_DIR.'assets/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css')}}" rel="stylesheet">
    <!-- toast CSS -->
    <link href="{{asset(STATIC_DIR.'assets/plugins/bower_components/toast-master/css/jquery.toast.css')}}" rel="stylesheet">



    <!-- animation CSS -->
    <link href="{{asset(STATIC_DIR.'assets/css/animate.css')}}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{asset(STATIC_DIR.'assets/css/style.css')}}" rel="stylesheet">
    <!-- color CSS -->
    <link href="{{asset(STATIC_DIR.'assets/css/colors/default.css')}}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    @yield('css')

</head>

resources/views/layouts/_partials/message.blade.php
@if(Session::has('success'))
<div class="alert alert-success alert-dismissable remove-message">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    {{Session::get('success')}}

</div>
@elseif(Session::has('error'))
    <div class="alert alert-danger alert-dismissable remove-message">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{Session::get('error')}}
    </div>
@endif


<script>
    setTimeout(function(){$('.remove-message').slideUp();},5000);  //slidup after 3 second
</script>

resources/views/layouts/_partials/nav.blade.php
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <div class="top-left-part">
            <!-- Logo -->
            <a class="logo" href="{{route('admin.user.list')}}">
                <!-- Logo icon image, you can use font-icon also --><b>
                    <!--This is dark logo icon--><img src="{{asset(STATIC_DIR.'assets/plugins/images/admin-logo.png')}}" alt="home" class="dark-logo" /><!--This is light logo icon--><img src="../plugins/images/admin-logo-dark.png" alt="home" class="light-logo" />
                </b>
                <!-- Logo text image you can use text also --><span class="hidden-xs">
                        <!--This is dark logo text--><img src="{{asset(STATIC_DIR.'assets/plugins/images/admin-text.png')}}" alt="home" class="dark-logo" /><!--This is light logo text--><img src="../plugins/images/admin-text-dark.png" alt="home" class="light-logo" />
                     </span> </a>
        </div>
        <!-- /Logo -->
        <!-- Search input and Toggle icon -->
        <ul class="nav navbar-top-links navbar-left">
            <li><a href="javascript:void(0)" class="open-close waves-effect waves-light visible-xs"><i class="ti-close ti-menu"></i></a></li>

        </ul>

        <ul class="nav navbar-top-links navbar-right pull-right">
            <li>
                <form role="search" class="app-search hidden-sm hidden-xs m-r-10">
                    <input type="text" placeholder="Search..." class="form-control"> <a href=""><i class="fa fa-search"></i></a> </form>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#">
                    @if(\Auth::user()->user_avatar == null)
                        <img src="{{asset(STATIC_DIR.'image_upload/default_user.png')}}"  alt="user-img" width="36" class="img-circle"><b class="hidden-xs">Steave</b><span class="caret"></span> </a>
                    @else
                        <img src="{{asset(STATIC_DIR.'storage/'.\Auth::user()->user_avatar)}}"  alt="user-img" width="36" class="img-circle"><b class="hidden-xs">Steave</b><span class="caret"></span> </a>

                    @endif
                <ul class="dropdown-menu dropdown-user animated flipInY">
                    <li>
                        <div class="dw-user-box">
                            <div class="u-img">
                                @if(\Auth::user()->user_avatar == null)
                                    <img src="{{asset(STATIC_DIR.'/image_upload/default_user.png')}}" alt="user" /></div>
                                @else
                                    <img src="{{asset(STATIC_DIR.'storage/'.\Auth::user()->user_avatar)}}" alt="" >
                                @endif
                            <div class="u-text">
                                <h4>{{ \Auth::user()->name }}</h4>
                                <p class="text-muted">{{ \Auth::user()->email}}</p><a href="profile.html" class="btn btn-rounded btn-danger btn-sm">View Profile</a>
                            </div>
                        </div>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#"><i class="ti-user"></i> My Profile</a></li>
                    <li>
                        <a href="" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="fa fa-power-off text-danger"></i> 
                            Logout
                        </a>
                    </li>

                        <form action="{{route('logout')}}" id="logout-form" method="POST">
                            @csrf
                                

                        </form>

                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
    </div>
    <!-- /.navbar-header -->
    <!-- /.navbar-top-links -->
    <!-- /.navbar-static-side -->
</nav>

resources/views/layouts/_partials/scripts.blade.php
<script src="{{asset(STATIC_DIR.'assets/plugins/bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{{asset(STATIC_DIR.'assets/bootstrap/dist/js/bootstrap.min.js')}}"></script>

<!-- Menu Plugin JavaScript -->
<script src="{{asset(STATIC_DIR.'assets/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js')}}"></script>

<!--slimscroll JavaScript -->
<script src="{{asset(STATIC_DIR.'assets/js/jquery.slimscroll.js')}}"></script>


<!--Wave Effects -->
<script src="{{asset(STATIC_DIR.'assets/js/waves.js')}}"></script>

<!-- Custom Theme JavaScript -->
<script src="{{asset(STATIC_DIR.'assets/js/custom.min.js')}}"></script>

$
@yield('scripts')

resources/views/layouts/_partials/sidebar.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav slimscrollsidebar">
        <div class="sidebar-head">
            <h3><span class="fa-fw open-close"><i class="ti-menu hidden-xs"></i><i class="ti-close visible-xs"></i></span> <span class="hide-menu">Navigation</span></h3> </div>
        <ul class="nav" id="side-menu">

            {{--<li>--}}
                {{--<a href="inbox.html" class="waves-effect"><i class="mdi mdi-apps fa-fw"></i> <span class="hide-menu">Apps<span class="fa arrow"></span></span></a>--}}
                {{--<ul class="nav nav-second-level">--}}
                    {{--<li><a href="chat.html"><i class="ti-comments-smiley fa-fw"></i><span class="hide-menu">Chat-message</span></a></li>--}}
                    {{--<li><a href="javascript:void(0)" class="waves-effect"><i class="ti-desktop fa-fw"></i><span class="hide-menu">Inbox</span><span class="fa arrow"></span></a>--}}
                        {{--<ul class="nav nav-third-level">--}}
                            {{--<li> <a href="inbox.html"><i class="ti-email fa-fw"></i><span class="hide-menu">Mail box</span></a></li>--}}
                            {{--<li> <a href="inbox-detail.html"><i class="ti-layout-media-left-alt fa-fw"></i><span class="hide-menu">Inbox detail</span></a></li>--}}
                            {{--<li> <a href="compose.html"><i class="ti-layout-media-center-alt fa-fw"></i><span class="hide-menu">Compose mail</span></a></li>--}}
                        {{--</ul>--}}
                    {{--</li>--}}
                    {{--<li><a href="javascript:void(0)" class="waves-effect"><i class="ti-user fa-fw"></i><span class="hide-menu">Contacts</span><span class="fa arrow"></span></a>--}}
                        {{--<ul class="nav nav-third-level">--}}
                            {{--<li> <a href="contact.html"><i class="icon-people fa-fw"></i><span class="hide-menu">Contact1</span></a></li>--}}
                            {{--<li> <a href="contact2.html"><i class="icon-user-follow fa-fw"></i><span class="hide-menu">Contact2</span></a></li>--}}
                            {{--<li> <a href="contact-detail.html"><i class="icon-user-following fa-fw"></i><span class="hide-menu">Contact Detail</span></a></li>--}}
                        {{--</ul>--}}
                    {{--</li>--}}
                {{--</ul>--}}
            {{--</li>--}}

            <li>
            <a href="inbox.html" class="waves-effect"><i class="mdi mdi-apps fa-fw"></i> <span class="hide-menu">Users<span class="fa arrow"></span></span></a>
            <ul class="nav nav-second-level">
            <li>
                <a href="{{route('register')}}">
                    <i class="ti-comments-smiley fa-fw"></i>
                    <span class="hide-menu">
                        Add User
                    </span>
                </a>
            </li>
            <li>
                <a href="{{route('admin.user.list')}}"><i class="ti-list fa-fw"></i>
                    <span class="hide-menu">List User</span>
                </a>
            </li>

            </ul>
            </li>

            <li class="devider"></li>
            @can('banner')
            <li> <a href="{{route('admin.banner.list')}}" class="waves-effect"><i  class="mdi mdi-home fa-fw"></i> <span class="hide-menu">Banner Management</span></a> </li>
            @endcan
            <li class="devider"></li>

            <li> <a href="{{route('admin.category.list')}}" class="waves-effect"><i  class="mdi mdi-blinds"></i> <span class="hide-menu"> Category Management</span></a> </li>

            <li class="devider"></li>

            <li> <a href="{{route('admin.product.list')}}" class="waves-effect"><i  class="mdi mdi-package-variant-closed fa-fw"></i> <span class="hide-menu">Product Management</span></a> </li>
            <li> <a href="widgets.html" class="waves-effect"><i  class="mdi mdi-package-variant-closed fa-fw"></i> <span class="hide-menu">Widgets</span></a> </li>


            {{--<li><a href="login.html" class="waves-effect"><i class="mdi mdi-logout fa-fw"></i> <span class="hide-menu">Log out</span></a></li>--}}

        </ul>
    </div>
</div>